server:
  port: 8768
spring:
  application:
    name: eureka-client-ribbon-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream