server:
  port: 8770
spring:
  application:
    name: eureka-client-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
turbine:
  aggregator:
    cluster-config: default
  app-config: eureka-client-ribbon-hystrix,eureka-client-feign-hystrix
  cluster-name-expression: new String("default")