server:
  port: 8801
spring:
  application:
    name: sleuth-client
  sleuth:
    sampler:
      probability: 1.0
    web:
      client:
        enabled: true
#  zipkin:
#    base-url: http://localhost:9411
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/