server:
  port: 8901
spring:
  application:
    name: spring-cloud-gateway
  profiles:
    active: my_route
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://httpbin.org:80
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  profiles: after_route

---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        #- id: one_route
        #  uri: http://httpbin.org:80
        #  filters:
        #    - One=true
        #    - Two=X-Request-Foo, Bar
        #  predicates:
        #    - Path=/get
        - id: two_route
          uri: lb://EUREKA-CLIENT
          filters:
            - One=true
            - Two=X-Request-Foo, Bar
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@uriKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
          predicates:
            - Path=/hello
  profiles: my_route
  redis:
    host: localhost
    port: 6379
